formCard(function renombrar, string nombreActual) {
    <mi-estilo>[
        T("Nombre actual: $nombreActual")
        FORM {
            INPUT_TEXT(
                id: "nuevoNombre",
                label: "Nuevo nombre",
                value: "$nombreActual"
            )
        } SUBMIT {
            label: "Guardar",
            function: $renombrar(@nuevoNombre)
        }
    ]
}

lista(string nombre) {
    <mi-estilo>[
        T("Pokemon: $nombre")
    ]
}